# Generated by Django 5.2.6 on 2025-09-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('ball', 'Ball'), ('accessories', 'Accessories'), ('training', 'Training'), ('merchandise', 'Merchandise'), ('protection', 'Protection')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
