# Generated by Django 5.2.6 on 2025-09-15 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default=0)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('ball', 'Ball'), ('accessories', 'Accessories'), ('training', 'Training'), ('merchandise', 'Merchandise'), ('protection', 'Protection')], default='Sport', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
