# Generated by Django 5.2.6 on 2025-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('ball', 'Ball'), ('accessories', 'Accessories'), ('training', 'Training'), ('merchandise', 'Merchandise'), ('protection', 'Protection'), ('choose category', 'Choose Category')], default='Choose Category', max_length=20),
        ),
    ]
