# Generated by Django 5.2.6 on 2025-09-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('ball', 'Ball'), ('accessories', 'Accessories'), ('training', 'Training'), ('merchandise', 'Merchandise'), ('protection', 'Protection'), ('-', '-')], default='-', max_length=20),
        ),
    ]
